config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "contributors#search"

  get '/search', to: 'contributors#search'
  post '/index', to: 'contributors#index'
  get '/send_pdf', to: 'contributors#send_pdf'
  get '/send_zip', to: 'contributors#send_zip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  def search; end

  def index
    service = GetContributorsService.new(params)
    service.call

    if service.error.nil?
      @value = service.value
      render :index
    else
      flash.now[:error] = service.error
      render :search
    end
  end

  def send_pdf
    service = GeneratePdfService.new(params)
    service.call

    if service.file
      send_data(service.file, filename: "diploma.pdf")
    else
      flash.now[:error] = I18n.t('errors.empty_cache')
      render :search
    end
  end

  def send_zip
    service = GenerateZipService.new(params)
    service.call

    if service.file
      send_data(service.file, filename: "diplomas.zip")
    else
      flash.now[:error] = I18n.t('errors.empty_cache')
      render :search
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributors/_form.html.erb
<%= form_for :contributors, url: index_path do |f| %>
  <%= f.text_field :str %>
  <%= f.submit "Find" %>
<% end %>

app/views/contributors/index.html.erb
<%= render 'form' %>

<% if @value[:source] %>
  <% @value[:result].each_with_index do |v, i| %>
    <p> 
      <%= v %> <%= link_to "download pdf", send_pdf_path(position: i, source: @value[:source]), target: :_blank %>
    </p>
  <% end %>
  <p>
    <%= link_to "download zip", send_zip_path(source: @value[:source]), target: :_blank %>
  </p>
<% end %>

app/views/contributors/search.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubContributors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <% unless flash[:error].blank? %>
      <div class="alert alert-danger">
        <p> <%= flash[:error] %> </p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>